/// Flutter icons WeatherIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcon
///      fonts:
///       - asset: fonts/WeatherIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherIcon {
  WeatherIcon._();

  static const _kFontFam = 'WeatherIcon';
  static const String? _kFontPkg = null;

  static const IconData a01d = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a01n = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a02d = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a02n = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a03d = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a03n = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a04d = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a04n = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a05n = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a05d = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a06d = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a06n = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c01d = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c01n = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c02d = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c02n = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c03d = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c03n = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c04d = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c04n = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d01d = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d01n = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d02d = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d02n = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d03d = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d03n = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f01d = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r01d = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f01n = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r01n = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r02d = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r02n = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r03d = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r03n = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r04d = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r04n = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r05n = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r06n = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s01d = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s01n = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s02d = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s02n = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s03d = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s03n = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s04d = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s04n = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s05d = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s05n = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t01d = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t01n = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t02d = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t02n = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t03d = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t03n = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t04d = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t04n = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t05d = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t05n2 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u00d = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v00n = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temp = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r05d = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r06d = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
